Dotnet Extension for Soot
soot-oss/soot pull request #1879
Opened 2022-06-22 14:39 UTC by jkluge

The following commits contain an extension for Soot to be able to analyze .Net CIL code. Therefore a (C++) bridge project can be specified, that calls a managed .Net runtime, which uses ILSpy to decompile the .dll / .exe files.

@StevenArzt

2022-06-27 18:41 UTC, StevenArzt requested changes

2022-06-27 18:41 UTC, StevenArzt commented on doc/soot_options.htm
> +            <td colspan="2">Ignore errors from method source and return empty jimple body</td>
Hier wäre es sinnvoller, wenn der Fake-Body eine entsprechende Exception werfen würde. Ansonsten hast du eine Methode mit Rückgabewert, die aber nichts zurückgibt.

2022-06-27 18:41 UTC, StevenArzt commented on doc/soot_options.htm
> +            <td colspan="2">Resolve all dotnet methods, such as unsafe methods</td>
Die Semantik ist unklar. Bitte besser erläutern.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/Body.java
> +  abstract public Object clone(boolean noLocalsClone);
Es wäre hübscher, wenn die ``clone`` Methode ohne Parameter die neue Methode aufrufen würde mit einem default-Wert statt beides abstrakt zu haben.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/BooleanType.java
> +    return "java.lang.Boolean";
Hübscher wäre analog zu dotNet eine Klasse JavaBasicTypes.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/EntryPoints.java
> +      sigMain = subSigNumberer.findOrAdd("void main(java.lang.String[])");
Das bitte wie bei Dotnet auslagern in eine Konstante

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/FastHierarchy.java
> +              if (!(methodParameter.equals(calleeParameter) || canStoreType(calleeParameter, methodParameter)))
Soot Coding Guidelines beachten, alle ``if`` Statements brauchen geschweifte Klammern, gibt sonst einen Build Failure von Style Checker.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/ModuleRefType.java
> +    if (getClassName().equals(Scene.v().getObjectType().toString()))
Den Namen kann man zwischenspeichern statt ihn zweimal zu berechnen

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/Scene.java
> +      determineExcludedPackages();
Gibt es für dotNet keine Systempakete, die man für normale Anwendungsanalysen ausschließen sollte?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/Scene.java
> +          else if (Options.v().src_prec() == Options.src_prec_dotnet)
Coding Guidelines

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/Scene.java
> +    if (excludedPackages == null)
heir kannst du auch prüfen, ob die Liste leer ist

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/Scene.java
> +                        RefType.v("java.lang.String"), 1));
auch für Java bitte Konstanten verwenden

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/SootClass.java
> +    if (name.length() == 0)
geschweifte Klammern, Soot Coding Guidelines

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/SootMethodRefImpl.java
> +    if (Options.v().src_prec() == Options.src_prec_dotnet)
Warum wird immer erst die Java-Exception erstellt und dann ggf. überschrieben? Das geht effizienter.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/SourceLocator.java
> +        classProviders.add(classFileClassProvider); //TODO remove
Warum steht hier ein TODO?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/baf/BafBody.java
> +    // not implemented
Das sollte implementiert werden

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dava/DavaBody.java
> +    // not implemented
Das sollte implementiert werden

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/DotnetClassProvider.java
> +                        if (!f.getCanonicalPath().endsWith(".exe") && !f.getCanonicalPath().endsWith(".dll"))
Groß-/Kleinschreibung ist bei der File Extension egal.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/DotnetClassSource.java
> +                if (st instanceof PrimType || st instanceof VoidType) {
Das ist Schlamperei. Man kann auch vorher prüfen, ob es sich um einen primitiven Typen handelt, bevor man versucht, die ``SootClass`` aufzulösen.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/DotnetClassSource.java
> +            String sootTypeName = st.toString();
Dafür gibt es bessere Lösungen per ``instanceof RefType`` und dann ``getSootClass()``

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/exceptiontoolkits/DotnetThrowAnalysis.java
> +     * Constructs a <code>DalvikThrowAnalysis</code> for inclusion in Soot's global variable manager, {@link G}.
Dalvik?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/exceptiontoolkits/DotnetThrowAnalysis.java
> +     * Returns the single instance of <code>DalvikThrowAnalysis</code>.
Dalvik?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/exceptiontoolkits/DotnetThrowAnalysis.java
> +                // result = result.add(Scene.v().getRefType(DotnetBasicTypes.SYSTEM_OUTOFMEMORYEXCEPTION));
Diese Zeile kann m.E. ganz raus

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/exceptiontoolkits/DotnetThrowAnalysis.java
> +                // result = mightThrowImplicitly(s);
Was ist mit dieser Zeile?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/exceptiontoolkits/DotnetThrowAnalysis.java
> +                // ignore, only refanyval
Ist mir unklar. Bitte entweder fixen oder besser kommentieren.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/exceptiontoolkits/DotnetThrowAnalysis.java
> +                    result = result.add(Scene.v().getRefType(DotnetBasicTypes.SYSTEM_INVALIDCASTEXCEPTION));
Kann die nicht auftreten, wenn ein ungültiger Cast zwischen zwei Refernztypen versucht wird?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/exceptiontoolkits/DotnetThrowAnalysis.java
> +                result = result.add(Scene.v().getRefType(v.getType().toString()));
Bitte nicht auf ``toString`` verlassen

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/exceptiontoolkits/DotnetThrowAnalysis.java
> +                // result = result.add(Scene.v().getRefType(DotnetBasicTypes.SYSTEM_SECURITYEXCEPTION));
Was ist mit dieser Exception?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CatchFilterHandlerBody.java
> +        AssignStmt assignStmt = Jimple.v().newAssignStmt(exceptionVar, generalExceptionVariable);
Das ``Jimple.v()`` kann man auch zwischenspeichern, wenn es häufiger gebraucht wird.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CatchHandlerBody.java
> +        Unit excStmt = Jimple.v().newIdentityStmt(exceptionVariable, Jimple.v().newCaughtExceptionRef());
``Jimple.v()`` bitte auch hier zwischenspeichern

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilCallVirtInstruction.java
> +        // constructor = virtualinvoke type.<System.Type: ConstructorInfo GetConstructor(System.Reflection.ParameterModifier[])>(modifiers);
Bitte prüfen, ob ein solcher impliziter Upcast wirklich möglich ist.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilCallVirtInstruction.java
> +        if (method.getReturnType().getTypeKind().equals(ProtoAssemblyAllTypes.TypeKindDef.POINTER)
Das Ergebnis von ``getReturnType()`` sollte zwischengespeichert werden.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilCkFiniteInstruction.java
> +        EqExpr eqPosInfExpr = Jimple.v().newEqExpr(argument, posInfinity);
``Jimple.v()`` zwischenspeichern

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilCkFiniteInstruction.java
> +        jb.getUnits().add(Jimple.v().newIfStmt(eqPosInfExpr, throwStmt));
``jb.getUnits()`` zwischenspeichern

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilDefaultValueInstruction.java
> +        // RefType refType = RefType.v(i.getType().getFullname());
Was ist mit diesem auskommentierten Code?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilIfInstruction.java
> +            jb.getUnits().add(Jimple.v().newAssignStmt(tmpLocalCond, condition));
``Jimple.v()`` zwischenspeichern

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilIfInstruction.java
> +        // dotnetBody.blockEntryPointsManager.gotoTargetsInBody.put(trueInstruct, target);
Was ist mit dieser auskommentierten Zeile?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilIsInstInstruction.java
> +        AssignStmt assignInstanceOfStmt = Jimple.v().newAssignStmt(local, instanceOfExpr);
``Jimple.v()`` zwischenspeichern

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilIsInstInstruction.java
> +        jb.getUnits().add(assignInstanceOfStmt);
``jb.getUnits()`` zwischenspeichern

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilLdTypeTokenInstruction.java
> +        // return StringConstant.v(i.getValueConstantString());
Die auskommentierte Zeile kann raus

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilLeaveInstruction.java
> +                // CilStLocInstruction stLocInstruction = new CilStLocInstruction(instruction, dotnetBody);
Was ist mit diesem auskommentierten Code?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilLeaveInstruction.java
> +                // CilStLocInstruction stLocInstruction = new CilStLocInstruction(instruction, dotnetBody);
auskommentierter Code?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilSizeOfInstruction.java
> +//        LocalGenerator localGenerator = new LocalGenerator(jb);
Bitte den auskommentierten Code rauswerfen, wenn er nicht benötigt wird.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilStLocInstruction.java
> +                && !variable.getType().toString().equals(value.getType().toString())
Warum werden hier die Strings verglichen?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilSwitchInstruction.java
> +                    // dotnetBody.blockEntryPointsManager.gotoTargetsInBody.put(nopStmt, section.getTargetInstr().getTargetLabel());
prüfen und ggf. die auskommentierte Zeile entfernen

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/instructions/CilSwitchInstruction.java
> +                        // dotnetBody.blockEntryPointsManager.gotoTargetsInBody.put(nopStmt, "END_" + section.getTargetInstr().getTargetLabel());
prüfen und ggf. entfernen

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/members/AbstractDotnetMember.java
> +            If System.Array.Empty, normal RefType(System.Array)
Ist mir unklar.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/members/DotnetEvent.java
> +                default: throw new RuntimeException("Unexpected selection of event method type!");
Bitte den unerwarteten Typen mit ausgeben

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/members/DotnetMethod.java
> +        methodName = methodName.replace("+", "$");
Das ist falsch herum, oder?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/members/method/DotnetBodyVariableManager.java
> +        if (this.mainJb.getLocals().stream().anyMatch(x -> x.getName().equals(v.getName())))
Das ``if`` ist unnötig

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/dotnet/types/DotnetTypeFactory.java
> +//        if (type.equals("nint"))
Wieso ist das auskommentiert?

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/grimp/GrimpBody.java
> +    // not implemented
Bitte implementieren

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/jbco/jimpleTransformations/BuildIntermediateAppClasses.java
> +                "void main(java.lang.String[])") && method.isPublic() && method.isStatic()) {
Bitte auch für die Java-Werte entsprechende Konstanten anlegen

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/jimple/internal/AbstractIntLongBinopExpr.java
> +      if (t1 instanceof RefType) {
Das ist in der ``AbstractFloatBinopExpr`` auch so drin. Bitte nach Duplikaten schauen und als Hilfsmethode in die gemeinsame Oberklasse übernehmen.

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/jimple/toolkits/callgraph/OnFlyCallGraphBuilder.java
> +        this.sigFinalize = nmbr.findOrAdd("void finalize()");
Die Java-Strings bitte auch als Konstanten auslagern

2022-06-27 18:41 UTC, StevenArzt commented on src/main/java/soot/shimple/ShimpleBody.java
> +    // not implemented
bitte implementieren

2022-06-28 11:09 UTC, jkluge commented on doc/soot_options.htm
> +            <td colspan="2">Ignore errors from method source and return empty jimple body</td>
Wenn diese Flag nicht auf true gesetzt ist, wird das ja auch getan. Soll ich das dann entfernen? Theoretisch kann es ja durchaus sinnvoll sein, keine Exceptions zu werfen, sondern nur Warnungen in den Logs zu bekommen.

2022-06-28 11:15 UTC, jkluge commented on src/main/java/soot/grimp/GrimpBody.java
> +    // not implemented
Was setzt denn die noLocalsClone Flag? Habe da keine Beispiele zu gefunden... Ich habe mir gedacht, dass sich das vermutlich darauf bezieht, ob nur der Body oder auch weitere Attribute mitgeclont werden sollen.

2022-06-28 11:22 UTC, jkluge commented on src/main/java/soot/shimple/ShimpleBody.java
> +    // not implemented
Wie auch schon oben angesprochen bin ich mir nicht sicher, ob das korrekt ist, wie ich es implementiere, aber ich gebe mal mein Bestes ^^

2022-06-28 11:30 UTC, jkluge commented on doc/soot_options.htm
> +            <td colspan="2">Ignore errors from method source and return empty jimple body</td>
Dann ist der Body der Methode halt leer, dafür können potentiell andere Methoden betrachtete werden.

2022-06-28 11:44 UTC, jkluge commented
Thomas hatte außerdem zu vielen Klassen noch keine Dokumentation geschrieben? Sollte das noch nachgeholt werden?

2022-06-28 12:52 UTC, StevenArzt commented on doc/soot_options.htm
> +            <td colspan="2">Ignore errors from method source and return empty jimple body</td>
So war das nicht gemeint. Statt eines leeren Bodies erzeugst du einen Body, der im Jimple-Code eine Exception wirft.

2022-06-28 12:53 UTC, StevenArzt commented on src/main/java/soot/grimp/GrimpBody.java
> +    // not implemented
Schau mal in den ``JimpleBody`` für ein Beispiel.

2022-06-28 12:53 UTC, StevenArzt commented on src/main/java/soot/shimple/ShimpleBody.java
> +    // not implemented
Schau mal in den ``JimpleBody`` für ein Beispiel.

2022-06-29 18:20 UTC, jkluge commented on doc/soot_options.htm
> +            <td colspan="2">Ignore errors from method source and return empty jimple body</td>
Ich füge im Jimple-Body also  einfach ein Throw-Statement hinzu, sodass die Methode keinen Rückgabewert liefert, richtig?

2022-06-29 18:21 UTC, jkluge commented on doc/soot_options.htm
> +            <td colspan="2">Ignore errors from method source and return empty jimple body</td>
Habe ich nun in DotnetBody.resolveEmptyBody implementiert

2022-06-30 20:59 UTC, StevenArzt approved these changes

2022-06-30 21:19 UTC, StevenArzt commented
Running the tests on the MR seems to be broken. Local tests look fine. I'll merge that for now. In case the build breaks, we have to either fix the issues quickly, or revert the MR.

2022-06-30 21:19 UTC, merged